apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    app: explorer
spec:
  type: ClusterIP
  selector:
    app: explorer
  ports:
  - protocol: TCP
    targetPort: 8080
    port: 8080