apiVersion: v1
kind: Service
metadata:
  name: explorer-db
  labels:
    app: explorer-db
spec:
  type: ClusterIP
  selector:
    app: explorer-db
  ports:
  - protocol: TCP
    targetPort: 5432
    port: 5432