apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabricfiles-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4050Mi
  selector:
    matchLabels:
      name: fabricfiles