---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka-broker-0
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: kafka
      podindex: "0"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka-broker-1
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: kafka
      podindex: "1"