---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-zoo-0
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: zookeeper
      podindex: "0"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-zoo-1
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: zookeeper
      podindex: "1"