apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-orderer
  labels:
    app: ca-orderer
spec:
  selector:
    matchLabels:
      app: ca-orderer
  replicas: 1
  template:
    metadata:
      labels:
        app: ca-orderer
    spec:
      containers:
      - name: ca-orderer
        image: hyperledger/fabric-ca:1.4.9
        imagePullPolicy: IfNotPresent
        command:
          [
            "fabric-ca-server",
            "start", "-b", "admin:adminpw", "--port", "10054", "-d"
          ]
        resources:
          requests:
            memory: "300Mi"
            cpu: "300m"
          limits:
            memory: "500Mi"
            cpu: "350m"
        ports:
          - containerPort: 10054
        env:
          - name: FABRIC_CA_SERVER_CA_NAME
            value: ca-orderer
          - name: FABRIC_CA_SERVER_TLS_ENABLED
            value: "true"
        volumeMounts:
          - name: data
            mountPath: /etc/hyperledger/fabric-ca-server
            subPath: organizations/fabric-ca/ordererOrg
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: fabricfiles-pvc
