apiVersion: v1
kind: Service
metadata:
  name: ca-org2
  labels:
    app: ca-org2
spec:
  type: ClusterIP
  selector:
    app: ca-org2 # deploymenti bu selector üzerinden bulur.deploymentdeki matchLabels ile aynı olmalı.
  ports:
  - protocol: TCP
    targetPort: 8054 # contanier portu
    port: 8054 # service portu
