apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broker
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: broker
  replicas: 2
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: broker
        image: hyperledger/fabric-kafka:0.4.21
        ports:
          - name: broker
            containerPort: 9092
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 5
          timeoutSeconds: 5
          failureThreshold: 6
          periodSeconds: 10
          successThreshold: 1
        env:
          - name: KAFKA_MESSAGE_MAX_BYTES
            value: "102760448"
          - name: KAFKA_REPLICA_FETCH_MAX_BYTES
            value: "102760448"
          - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
            value: "false"
          - name: KAFKA_DEFAULT_REPLICATION_FACTOR
            value: "2"
          - name: KAFKA_MIN_INSYNC_REPLICAS
            value: "2"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zoo-0.zoo:2181,zoo-1.zoo:2181
          - name: KAFKA_PORT
            value: "9092"
          - name: GODEBUG
            value: netdns=go   
          - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
            value: "30000"
          - name: KAFKA_LOG_DIRS
            value: /opt/kafka/data
        volumeMounts:
          - name: kafka
            mountPath: /opt/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: kafka