apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - name: client
      protocol: TCP
      targetPort: 2181
      port: 2181

---
#---------------- Zookeper Headless Service ---------------
apiVersion: v1
kind: Service
metadata:
  name: zoo
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: zookeeper
  ports:
  - name: "peer"
    targetPort: 2888 # container metric portu
    port: 2888
  - name: "leader-election"
    targetPort: 3888 # container metric portu
    port: 3888