apiVersion: v1
kind: Service
metadata:
  name: orderer4
  labels: 
    app: orderer4
spec:
  type: ClusterIP
  selector:
    app: orderer4 # deploymenti bu selector üzerinden bulur.deploymentdeki matchLabels ile aynı olmalı.
  ports:
  - name: grpc
    protocol: TCP
    targetPort: 7050 # contanier portu
    port: 7050 # service portu

---
#---------------- Orderer4 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  name: orderer4-metrics
  labels:
    app: orderer4
    metrics-service: "true"
spec:
  type: ClusterIP
  selector:
    app: orderer4
  ports:
  - name: "orderer4-metrics"
    targetPort: 9444 # container metric portu
    port: 9444