apiVersion: v1
kind: Service
metadata:
  name: orderer3
  labels: 
    app: orderer3
spec:
  type: ClusterIP
  selector:
    app: orderer3 # deploymenti bu selector üzerinden bulur.deploymentdeki matchLabels ile aynı olmalı.
  ports:
  - name: grpc
    protocol: TCP
    targetPort: 7050 # contanier portu
    port: 7050 # service portu

---
#---------------- Orderer3 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  name: orderer3-metrics
  labels:
    app: orderer3
    metrics-service: "true"
spec:
  type: ClusterIP
  selector:
    app: orderer3
  ports:
  - name: "orderer3-metrics"
    targetPort: 9444 # container metric portu
    port: 9444