apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: suayb/hlf-frontend:1.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "250Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"
        ports:
        - containerPort: 80
