apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabricfiles-pv
  labels:
    name: fabricfiles
spec:
  storageClassName: default
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share/fabricfiles
    server: 192.168.12.20