---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka0-pv
  labels:
    app: kafka
    podindex: "0"
spec:
  storageClassName: default
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/kubedata/fabricfiles/broker/kafka0
    server: 192.168.12.9

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka1-pv
  labels:
    app: kafka
    podindex: "1"
spec:
  storageClassName: default
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/kubedata/fabricfiles/broker/kafka1
    server: 192.168.12.9